apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-config
  namespace: monitoring
stringData:
  alertmanager.yaml: |
    global:
      smtp_smarthost: "email-smtp.us-east-1.amazonaws.com:587"
      smtp_from: "svadrevu@umd.edu"
      smtp_auth_username: "AKIA45Y2RLV7WQ63BCU4"
      smtp_auth_password: "BJmVulOYYjvPCmpcLdQbLkI55XD6MnXRuJi2uQ/b9mQS"
      smtp_require_tls: true
    route:
      receiver: "null-receiver"  # Default receiver for unmatched alerts
      group_by: ['alertname']
      routes:
        - receiver: "email-alert"
          matchers:
            - alertname="PodRestartCountHigh"
          group_wait: 30s
          group_interval: 5m
          repeat_interval: 12h
    receivers:
      - name: "email-alert"
        email_configs:
          - to: "svadrevu@umd.edu"
            send_resolved: true
            html: |
              <b>{{ .CommonAnnotations.summary }}</b><br>
              <p>{{ .CommonAnnotations.description }}</p>
      - name: "null-receiver"